# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reference_pb2 as reference__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTariff = channel.unary_unary(
                '/ReferenceService/GetTariff',
                request_serializer=reference__pb2.TariffRequest.SerializeToString,
                response_deserializer=reference__pb2.TariffResponse.FromString,
                _registered_method=True)
        self.ValidateAddress = channel.unary_unary(
                '/ReferenceService/ValidateAddress',
                request_serializer=reference__pb2.AddressRequest.SerializeToString,
                response_deserializer=reference__pb2.ValidationResponse.FromString,
                _registered_method=True)
        self.GetVehicleTypes = channel.unary_unary(
                '/ReferenceService/GetVehicleTypes',
                request_serializer=reference__pb2.Empty.SerializeToString,
                response_deserializer=reference__pb2.VehicleTypesResponse.FromString,
                _registered_method=True)


class ReferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTariff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTariff': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTariff,
                    request_deserializer=reference__pb2.TariffRequest.FromString,
                    response_serializer=reference__pb2.TariffResponse.SerializeToString,
            ),
            'ValidateAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAddress,
                    request_deserializer=reference__pb2.AddressRequest.FromString,
                    response_serializer=reference__pb2.ValidationResponse.SerializeToString,
            ),
            'GetVehicleTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleTypes,
                    request_deserializer=reference__pb2.Empty.FromString,
                    response_serializer=reference__pb2.VehicleTypesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ReferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTariff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReferenceService/GetTariff',
            reference__pb2.TariffRequest.SerializeToString,
            reference__pb2.TariffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReferenceService/ValidateAddress',
            reference__pb2.AddressRequest.SerializeToString,
            reference__pb2.ValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVehicleTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReferenceService/GetVehicleTypes',
            reference__pb2.Empty.SerializeToString,
            reference__pb2.VehicleTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
