# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0freference.proto\"E\n\rTariffRequest\x12\x0c\n\x04zone\x18\x01 \x01(\t\x12\x11\n\tweight_kg\x18\x02 \x01(\x01\x12\x13\n\x0b\x64istance_km\x18\x03 \x01(\x01\"M\n\x0eTariffResponse\x12\x13\n\x0b\x63ost_per_km\x18\x01 \x01(\x01\x12\x13\n\x0b\x63ost_per_kg\x18\x02 \x01(\x01\x12\x11\n\tbase_cost\x18\x03 \x01(\x01\"!\n\x0e\x41\x64\x64ressRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"7\n\x12ValidationResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\">\n\x0bVehicleType\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rmax_weight_kg\x18\x03 \x01(\x01\"3\n\x14VehicleTypesResponse\x12\x1b\n\x05types\x18\x01 \x03(\x0b\x32\x0c.VehicleType2\xab\x01\n\x10ReferenceService\x12,\n\tGetTariff\x12\x0e.TariffRequest\x1a\x0f.TariffResponse\x12\x37\n\x0fValidateAddress\x12\x0f.AddressRequest\x1a\x13.ValidationResponse\x12\x30\n\x0fGetVehicleTypes\x12\x06.Empty\x1a\x15.VehicleTypesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TARIFFREQUEST']._serialized_start=19
  _globals['_TARIFFREQUEST']._serialized_end=88
  _globals['_TARIFFRESPONSE']._serialized_start=90
  _globals['_TARIFFRESPONSE']._serialized_end=167
  _globals['_ADDRESSREQUEST']._serialized_start=169
  _globals['_ADDRESSREQUEST']._serialized_end=202
  _globals['_VALIDATIONRESPONSE']._serialized_start=204
  _globals['_VALIDATIONRESPONSE']._serialized_end=259
  _globals['_EMPTY']._serialized_start=261
  _globals['_EMPTY']._serialized_end=268
  _globals['_VEHICLETYPE']._serialized_start=270
  _globals['_VEHICLETYPE']._serialized_end=332
  _globals['_VEHICLETYPESRESPONSE']._serialized_start=334
  _globals['_VEHICLETYPESRESPONSE']._serialized_end=385
  _globals['_REFERENCESERVICE']._serialized_start=388
  _globals['_REFERENCESERVICE']._serialized_end=559
# @@protoc_insertion_point(module_scope)
