# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hospital.proto
# Protobuf Python Version: 6.31.1

# классы сообщений запросы и ответы
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hospital.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehospital.proto\x12\x08hospital\"\x07\n\x05\x45mpty\"%\n\x10GetDoctorRequest\x12\x11\n\tdoctor_id\x18\x01 \x01(\x05\"8\n\x10\x41\x64\x64\x44octorRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0especialization\x18\x02 \x01(\t\"R\n\x0e\x44octorResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x16\n\x0especialization\x18\x04 \x01(\t\"?\n\x12\x44octorListResponse\x12)\n\x07\x64octors\x18\x01 \x03(\x0b\x32\x18.hospital.DoctorResponse\"!\n\x0eGetWardRequest\x12\x0f\n\x07ward_id\x18\x01 \x01(\x05\"L\n\x0cWardResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0e\n\x06number\x18\x03 \x01(\x05\x12\x10\n\x08\x63\x61pacity\x18\x04 \x01(\x05\x32\x93\x02\n\x10ReferenceService\x12\x41\n\tGetDoctor\x12\x1a.hospital.GetDoctorRequest\x1a\x18.hospital.DoctorResponse\x12;\n\x07GetWard\x12\x18.hospital.GetWardRequest\x1a\x16.hospital.WardResponse\x12\x41\n\tAddDoctor\x12\x1a.hospital.AddDoctorRequest\x1a\x18.hospital.DoctorResponse\x12<\n\x0bListDoctors\x12\x0f.hospital.Empty\x1a\x1c.hospital.DoctorListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hospital_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_GETDOCTORREQUEST']._serialized_start=37
  _globals['_GETDOCTORREQUEST']._serialized_end=74
  _globals['_ADDDOCTORREQUEST']._serialized_start=76
  _globals['_ADDDOCTORREQUEST']._serialized_end=132
  _globals['_DOCTORRESPONSE']._serialized_start=134
  _globals['_DOCTORRESPONSE']._serialized_end=216
  _globals['_DOCTORLISTRESPONSE']._serialized_start=218
  _globals['_DOCTORLISTRESPONSE']._serialized_end=281
  _globals['_GETWARDREQUEST']._serialized_start=283
  _globals['_GETWARDREQUEST']._serialized_end=316
  _globals['_WARDRESPONSE']._serialized_start=318
  _globals['_WARDRESPONSE']._serialized_end=394
  _globals['_REFERENCESERVICE']._serialized_start=397
  _globals['_REFERENCESERVICE']._serialized_end=672
# @@protoc_insertion_point(module_scope)
