# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hospital_pb2 as hospital__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hospital_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReferenceServiceStub(object):
    """Сервис справочников (Service B)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDoctor = channel.unary_unary(
                '/hospital.ReferenceService/GetDoctor',
                request_serializer=hospital__pb2.GetDoctorRequest.SerializeToString,
                response_deserializer=hospital__pb2.DoctorResponse.FromString,
                _registered_method=True)
        self.GetWard = channel.unary_unary(
                '/hospital.ReferenceService/GetWard',
                request_serializer=hospital__pb2.GetWardRequest.SerializeToString,
                response_deserializer=hospital__pb2.WardResponse.FromString,
                _registered_method=True)
        self.AddDoctor = channel.unary_unary(
                '/hospital.ReferenceService/AddDoctor',
                request_serializer=hospital__pb2.AddDoctorRequest.SerializeToString,
                response_deserializer=hospital__pb2.DoctorResponse.FromString,
                _registered_method=True)
        self.ListDoctors = channel.unary_unary(
                '/hospital.ReferenceService/ListDoctors',
                request_serializer=hospital__pb2.Empty.SerializeToString,
                response_deserializer=hospital__pb2.DoctorListResponse.FromString,
                _registered_method=True)


class ReferenceServiceServicer(object):
    """Сервис справочников (Service B)
    """

    def GetDoctor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDoctor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDoctors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDoctor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDoctor,
                    request_deserializer=hospital__pb2.GetDoctorRequest.FromString,
                    response_serializer=hospital__pb2.DoctorResponse.SerializeToString,
            ),
            'GetWard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWard,
                    request_deserializer=hospital__pb2.GetWardRequest.FromString,
                    response_serializer=hospital__pb2.WardResponse.SerializeToString,
            ),
            'AddDoctor': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDoctor,
                    request_deserializer=hospital__pb2.AddDoctorRequest.FromString,
                    response_serializer=hospital__pb2.DoctorResponse.SerializeToString,
            ),
            'ListDoctors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDoctors,
                    request_deserializer=hospital__pb2.Empty.FromString,
                    response_serializer=hospital__pb2.DoctorListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hospital.ReferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hospital.ReferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReferenceService(object):
    """Сервис справочников (Service B)
    """

    @staticmethod
    def GetDoctor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.ReferenceService/GetDoctor',
            hospital__pb2.GetDoctorRequest.SerializeToString,
            hospital__pb2.DoctorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.ReferenceService/GetWard',
            hospital__pb2.GetWardRequest.SerializeToString,
            hospital__pb2.WardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddDoctor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.ReferenceService/AddDoctor',
            hospital__pb2.AddDoctorRequest.SerializeToString,
            hospital__pb2.DoctorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDoctors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.ReferenceService/ListDoctors',
            hospital__pb2.Empty.SerializeToString,
            hospital__pb2.DoctorListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
