# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0freference.proto\x12\treference\"[\n\x0fValidateRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x12\n\npatient_id\x18\x02 \x01(\t\x12\x11\n\tdoctor_id\x18\x03 \x01(\t\x12\x0f\n\x07ward_id\x18\x04 \x01(\t\"g\n\x10ValidateResponse\x12\x16\n\x0epatient_exists\x18\x01 \x01(\x08\x12\x15\n\rdoctor_exists\x18\x02 \x01(\x08\x12\x13\n\x0bward_exists\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\")\n\tIdRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"\x1d\n\x0cNameResponse\x12\r\n\x05value\x18\x01 \x01(\t2\x9d\x02\n\x12ReferenceValidator\x12\x46\n\x0bValidateIds\x12\x1a.reference.ValidateRequest\x1a\x1b.reference.ValidateResponse\x12?\n\x0eGetPatientName\x12\x14.reference.IdRequest\x1a\x17.reference.NameResponse\x12>\n\rGetDoctorName\x12\x14.reference.IdRequest\x1a\x17.reference.NameResponse\x12>\n\rGetWardNumber\x12\x14.reference.IdRequest\x1a\x17.reference.NameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEREQUEST']._serialized_start=30
  _globals['_VALIDATEREQUEST']._serialized_end=121
  _globals['_VALIDATERESPONSE']._serialized_start=123
  _globals['_VALIDATERESPONSE']._serialized_end=226
  _globals['_IDREQUEST']._serialized_start=228
  _globals['_IDREQUEST']._serialized_end=269
  _globals['_NAMERESPONSE']._serialized_start=271
  _globals['_NAMERESPONSE']._serialized_end=300
  _globals['_REFERENCEVALIDATOR']._serialized_start=303
  _globals['_REFERENCEVALIDATOR']._serialized_end=588
# @@protoc_insertion_point(module_scope)
