
discount.excellent.threshold=4.5
discount.good.threshold=4.0

discount.excellent.percent=15
discount.good.percent=10

discount.min.grades.count=3

discount.excellent.promo=EXCELLENT!!!
discount.good.promo=GOOD
discount.no.discount.promo=NO_DISCOUNT