// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface BrandListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.BrandListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .reference.BrandResponse brands = 1;</code>
   */
  java.util.List<gruzomarket.reference.grpc.BrandResponse> 
      getBrandsList();
  /**
   * <code>repeated .reference.BrandResponse brands = 1;</code>
   */
  gruzomarket.reference.grpc.BrandResponse getBrands(int index);
  /**
   * <code>repeated .reference.BrandResponse brands = 1;</code>
   */
  int getBrandsCount();
  /**
   * <code>repeated .reference.BrandResponse brands = 1;</code>
   */
  java.util.List<? extends gruzomarket.reference.grpc.BrandResponseOrBuilder> 
      getBrandsOrBuilderList();
  /**
   * <code>repeated .reference.BrandResponse brands = 1;</code>
   */
  gruzomarket.reference.grpc.BrandResponseOrBuilder getBrandsOrBuilder(
      int index);
}
