// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface BrandResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.BrandResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 product_count = 3;</code>
   * @return The productCount.
   */
  int getProductCount();
}
