// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

/**
 * Protobuf type {@code reference.CategoryListResponse}
 */
public final class CategoryListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:reference.CategoryListResponse)
    CategoryListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CategoryListResponse.newBuilder() to construct.
  private CategoryListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CategoryListResponse() {
    categories_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CategoryListResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_CategoryListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_CategoryListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gruzomarket.reference.grpc.CategoryListResponse.class, gruzomarket.reference.grpc.CategoryListResponse.Builder.class);
  }

  public static final int CATEGORIES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<gruzomarket.reference.grpc.CategoryResponse> categories_;
  /**
   * <code>repeated .reference.CategoryResponse categories = 1;</code>
   */
  @java.lang.Override
  public java.util.List<gruzomarket.reference.grpc.CategoryResponse> getCategoriesList() {
    return categories_;
  }
  /**
   * <code>repeated .reference.CategoryResponse categories = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends gruzomarket.reference.grpc.CategoryResponseOrBuilder> 
      getCategoriesOrBuilderList() {
    return categories_;
  }
  /**
   * <code>repeated .reference.CategoryResponse categories = 1;</code>
   */
  @java.lang.Override
  public int getCategoriesCount() {
    return categories_.size();
  }
  /**
   * <code>repeated .reference.CategoryResponse categories = 1;</code>
   */
  @java.lang.Override
  public gruzomarket.reference.grpc.CategoryResponse getCategories(int index) {
    return categories_.get(index);
  }
  /**
   * <code>repeated .reference.CategoryResponse categories = 1;</code>
   */
  @java.lang.Override
  public gruzomarket.reference.grpc.CategoryResponseOrBuilder getCategoriesOrBuilder(
      int index) {
    return categories_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < categories_.size(); i++) {
      output.writeMessage(1, categories_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < categories_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, categories_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gruzomarket.reference.grpc.CategoryListResponse)) {
      return super.equals(obj);
    }
    gruzomarket.reference.grpc.CategoryListResponse other = (gruzomarket.reference.grpc.CategoryListResponse) obj;

    if (!getCategoriesList()
        .equals(other.getCategoriesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCategoriesCount() > 0) {
      hash = (37 * hash) + CATEGORIES_FIELD_NUMBER;
      hash = (53 * hash) + getCategoriesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gruzomarket.reference.grpc.CategoryListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gruzomarket.reference.grpc.CategoryListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.CategoryListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gruzomarket.reference.grpc.CategoryListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.CategoryListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gruzomarket.reference.grpc.CategoryListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.CategoryListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gruzomarket.reference.grpc.CategoryListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.CategoryListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gruzomarket.reference.grpc.CategoryListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.CategoryListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gruzomarket.reference.grpc.CategoryListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gruzomarket.reference.grpc.CategoryListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reference.CategoryListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reference.CategoryListResponse)
      gruzomarket.reference.grpc.CategoryListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_CategoryListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_CategoryListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gruzomarket.reference.grpc.CategoryListResponse.class, gruzomarket.reference.grpc.CategoryListResponse.Builder.class);
    }

    // Construct using gruzomarket.reference.grpc.CategoryListResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (categoriesBuilder_ == null) {
        categories_ = java.util.Collections.emptyList();
      } else {
        categories_ = null;
        categoriesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_CategoryListResponse_descriptor;
    }

    @java.lang.Override
    public gruzomarket.reference.grpc.CategoryListResponse getDefaultInstanceForType() {
      return gruzomarket.reference.grpc.CategoryListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public gruzomarket.reference.grpc.CategoryListResponse build() {
      gruzomarket.reference.grpc.CategoryListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gruzomarket.reference.grpc.CategoryListResponse buildPartial() {
      gruzomarket.reference.grpc.CategoryListResponse result = new gruzomarket.reference.grpc.CategoryListResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(gruzomarket.reference.grpc.CategoryListResponse result) {
      if (categoriesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          categories_ = java.util.Collections.unmodifiableList(categories_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.categories_ = categories_;
      } else {
        result.categories_ = categoriesBuilder_.build();
      }
    }

    private void buildPartial0(gruzomarket.reference.grpc.CategoryListResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gruzomarket.reference.grpc.CategoryListResponse) {
        return mergeFrom((gruzomarket.reference.grpc.CategoryListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gruzomarket.reference.grpc.CategoryListResponse other) {
      if (other == gruzomarket.reference.grpc.CategoryListResponse.getDefaultInstance()) return this;
      if (categoriesBuilder_ == null) {
        if (!other.categories_.isEmpty()) {
          if (categories_.isEmpty()) {
            categories_ = other.categories_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCategoriesIsMutable();
            categories_.addAll(other.categories_);
          }
          onChanged();
        }
      } else {
        if (!other.categories_.isEmpty()) {
          if (categoriesBuilder_.isEmpty()) {
            categoriesBuilder_.dispose();
            categoriesBuilder_ = null;
            categories_ = other.categories_;
            bitField0_ = (bitField0_ & ~0x00000001);
            categoriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCategoriesFieldBuilder() : null;
          } else {
            categoriesBuilder_.addAllMessages(other.categories_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              gruzomarket.reference.grpc.CategoryResponse m =
                  input.readMessage(
                      gruzomarket.reference.grpc.CategoryResponse.parser(),
                      extensionRegistry);
              if (categoriesBuilder_ == null) {
                ensureCategoriesIsMutable();
                categories_.add(m);
              } else {
                categoriesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<gruzomarket.reference.grpc.CategoryResponse> categories_ =
      java.util.Collections.emptyList();
    private void ensureCategoriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        categories_ = new java.util.ArrayList<gruzomarket.reference.grpc.CategoryResponse>(categories_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        gruzomarket.reference.grpc.CategoryResponse, gruzomarket.reference.grpc.CategoryResponse.Builder, gruzomarket.reference.grpc.CategoryResponseOrBuilder> categoriesBuilder_;

    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public java.util.List<gruzomarket.reference.grpc.CategoryResponse> getCategoriesList() {
      if (categoriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(categories_);
      } else {
        return categoriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public int getCategoriesCount() {
      if (categoriesBuilder_ == null) {
        return categories_.size();
      } else {
        return categoriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public gruzomarket.reference.grpc.CategoryResponse getCategories(int index) {
      if (categoriesBuilder_ == null) {
        return categories_.get(index);
      } else {
        return categoriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public Builder setCategories(
        int index, gruzomarket.reference.grpc.CategoryResponse value) {
      if (categoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategoriesIsMutable();
        categories_.set(index, value);
        onChanged();
      } else {
        categoriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public Builder setCategories(
        int index, gruzomarket.reference.grpc.CategoryResponse.Builder builderForValue) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        categories_.set(index, builderForValue.build());
        onChanged();
      } else {
        categoriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public Builder addCategories(gruzomarket.reference.grpc.CategoryResponse value) {
      if (categoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategoriesIsMutable();
        categories_.add(value);
        onChanged();
      } else {
        categoriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public Builder addCategories(
        int index, gruzomarket.reference.grpc.CategoryResponse value) {
      if (categoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategoriesIsMutable();
        categories_.add(index, value);
        onChanged();
      } else {
        categoriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public Builder addCategories(
        gruzomarket.reference.grpc.CategoryResponse.Builder builderForValue) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        categories_.add(builderForValue.build());
        onChanged();
      } else {
        categoriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public Builder addCategories(
        int index, gruzomarket.reference.grpc.CategoryResponse.Builder builderForValue) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        categories_.add(index, builderForValue.build());
        onChanged();
      } else {
        categoriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public Builder addAllCategories(
        java.lang.Iterable<? extends gruzomarket.reference.grpc.CategoryResponse> values) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, categories_);
        onChanged();
      } else {
        categoriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public Builder clearCategories() {
      if (categoriesBuilder_ == null) {
        categories_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        categoriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public Builder removeCategories(int index) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        categories_.remove(index);
        onChanged();
      } else {
        categoriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public gruzomarket.reference.grpc.CategoryResponse.Builder getCategoriesBuilder(
        int index) {
      return getCategoriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public gruzomarket.reference.grpc.CategoryResponseOrBuilder getCategoriesOrBuilder(
        int index) {
      if (categoriesBuilder_ == null) {
        return categories_.get(index);  } else {
        return categoriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public java.util.List<? extends gruzomarket.reference.grpc.CategoryResponseOrBuilder> 
         getCategoriesOrBuilderList() {
      if (categoriesBuilder_ != null) {
        return categoriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(categories_);
      }
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public gruzomarket.reference.grpc.CategoryResponse.Builder addCategoriesBuilder() {
      return getCategoriesFieldBuilder().addBuilder(
          gruzomarket.reference.grpc.CategoryResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public gruzomarket.reference.grpc.CategoryResponse.Builder addCategoriesBuilder(
        int index) {
      return getCategoriesFieldBuilder().addBuilder(
          index, gruzomarket.reference.grpc.CategoryResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .reference.CategoryResponse categories = 1;</code>
     */
    public java.util.List<gruzomarket.reference.grpc.CategoryResponse.Builder> 
         getCategoriesBuilderList() {
      return getCategoriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        gruzomarket.reference.grpc.CategoryResponse, gruzomarket.reference.grpc.CategoryResponse.Builder, gruzomarket.reference.grpc.CategoryResponseOrBuilder> 
        getCategoriesFieldBuilder() {
      if (categoriesBuilder_ == null) {
        categoriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            gruzomarket.reference.grpc.CategoryResponse, gruzomarket.reference.grpc.CategoryResponse.Builder, gruzomarket.reference.grpc.CategoryResponseOrBuilder>(
                categories_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        categories_ = null;
      }
      return categoriesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:reference.CategoryListResponse)
  }

  // @@protoc_insertion_point(class_scope:reference.CategoryListResponse)
  private static final gruzomarket.reference.grpc.CategoryListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gruzomarket.reference.grpc.CategoryListResponse();
  }

  public static gruzomarket.reference.grpc.CategoryListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CategoryListResponse>
      PARSER = new com.google.protobuf.AbstractParser<CategoryListResponse>() {
    @java.lang.Override
    public CategoryListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CategoryListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CategoryListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gruzomarket.reference.grpc.CategoryListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

