// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface CategoryListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.CategoryListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .reference.CategoryResponse categories = 1;</code>
   */
  java.util.List<gruzomarket.reference.grpc.CategoryResponse> 
      getCategoriesList();
  /**
   * <code>repeated .reference.CategoryResponse categories = 1;</code>
   */
  gruzomarket.reference.grpc.CategoryResponse getCategories(int index);
  /**
   * <code>repeated .reference.CategoryResponse categories = 1;</code>
   */
  int getCategoriesCount();
  /**
   * <code>repeated .reference.CategoryResponse categories = 1;</code>
   */
  java.util.List<? extends gruzomarket.reference.grpc.CategoryResponseOrBuilder> 
      getCategoriesOrBuilderList();
  /**
   * <code>repeated .reference.CategoryResponse categories = 1;</code>
   */
  gruzomarket.reference.grpc.CategoryResponseOrBuilder getCategoriesOrBuilder(
      int index);
}
