// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface CategoryGroupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.CategoryGroupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group_name = 1;</code>
   * @return The groupName.
   */
  java.lang.String getGroupName();
  /**
   * <code>string group_name = 1;</code>
   * @return The bytes for groupName.
   */
  com.google.protobuf.ByteString
      getGroupNameBytes();

  /**
   * <code>repeated .reference.CategoryResponse categories = 2;</code>
   */
  java.util.List<gruzomarket.reference.grpc.CategoryResponse> 
      getCategoriesList();
  /**
   * <code>repeated .reference.CategoryResponse categories = 2;</code>
   */
  gruzomarket.reference.grpc.CategoryResponse getCategories(int index);
  /**
   * <code>repeated .reference.CategoryResponse categories = 2;</code>
   */
  int getCategoriesCount();
  /**
   * <code>repeated .reference.CategoryResponse categories = 2;</code>
   */
  java.util.List<? extends gruzomarket.reference.grpc.CategoryResponseOrBuilder> 
      getCategoriesOrBuilderList();
  /**
   * <code>repeated .reference.CategoryResponse categories = 2;</code>
   */
  gruzomarket.reference.grpc.CategoryResponseOrBuilder getCategoriesOrBuilder(
      int index);
}
