// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface CategoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.CategoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 parent_id = 3;</code>
   * @return The parentId.
   */
  long getParentId();

  /**
   * <code>int32 product_count = 4;</code>
   * @return The productCount.
   */
  int getProductCount();

  /**
   * <code>string image_url = 5;</code>
   * @return The imageUrl.
   */
  java.lang.String getImageUrl();
  /**
   * <code>string image_url = 5;</code>
   * @return The bytes for imageUrl.
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();
}
