// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface CategoryGroupListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.CategoryGroupListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .reference.CategoryGroupResponse groups = 1;</code>
   */
  java.util.List<gruzomarket.reference.grpc.CategoryGroupResponse> 
      getGroupsList();
  /**
   * <code>repeated .reference.CategoryGroupResponse groups = 1;</code>
   */
  gruzomarket.reference.grpc.CategoryGroupResponse getGroups(int index);
  /**
   * <code>repeated .reference.CategoryGroupResponse groups = 1;</code>
   */
  int getGroupsCount();
  /**
   * <code>repeated .reference.CategoryGroupResponse groups = 1;</code>
   */
  java.util.List<? extends gruzomarket.reference.grpc.CategoryGroupResponseOrBuilder> 
      getGroupsOrBuilderList();
  /**
   * <code>repeated .reference.CategoryGroupResponse groups = 1;</code>
   */
  gruzomarket.reference.grpc.CategoryGroupResponseOrBuilder getGroupsOrBuilder(
      int index);
}
