// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface ExistsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.ExistsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool exists = 1;</code>
   * @return The exists.
   */
  boolean getExists();
}
