// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface GetBrandsByProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.GetBrandsByProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 product_id = 1;</code>
   * @return The productId.
   */
  long getProductId();
}
