// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface GetProductCategoryIdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.GetProductCategoryIdsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 product_ids = 1;</code>
   * @return A list containing the productIds.
   */
  java.util.List<java.lang.Long> getProductIdsList();
  /**
   * <code>repeated int64 product_ids = 1;</code>
   * @return The count of productIds.
   */
  int getProductIdsCount();
  /**
   * <code>repeated int64 product_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The productIds at the given index.
   */
  long getProductIds(int index);
}
