// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface GetProductsByBrandRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.GetProductsByBrandRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 brand_id = 1;</code>
   * @return The brandId.
   */
  long getBrandId();
}
