// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

/**
 * Protobuf type {@code reference.GetProductCategoryIdsRequest}
 */
public final class GetProductCategoryIdsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:reference.GetProductCategoryIdsRequest)
    GetProductCategoryIdsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetProductCategoryIdsRequest.newBuilder() to construct.
  private GetProductCategoryIdsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetProductCategoryIdsRequest() {
    productIds_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetProductCategoryIdsRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_GetProductCategoryIdsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_GetProductCategoryIdsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gruzomarket.reference.grpc.GetProductCategoryIdsRequest.class, gruzomarket.reference.grpc.GetProductCategoryIdsRequest.Builder.class);
  }

  public static final int PRODUCT_IDS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList productIds_;
  /**
   * <code>repeated int64 product_ids = 1;</code>
   * @return A list containing the productIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getProductIdsList() {
    return productIds_;
  }
  /**
   * <code>repeated int64 product_ids = 1;</code>
   * @return The count of productIds.
   */
  public int getProductIdsCount() {
    return productIds_.size();
  }
  /**
   * <code>repeated int64 product_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The productIds at the given index.
   */
  public long getProductIds(int index) {
    return productIds_.getLong(index);
  }
  private int productIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getProductIdsList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(productIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < productIds_.size(); i++) {
      output.writeInt64NoTag(productIds_.getLong(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < productIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(productIds_.getLong(i));
      }
      size += dataSize;
      if (!getProductIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      productIdsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gruzomarket.reference.grpc.GetProductCategoryIdsRequest)) {
      return super.equals(obj);
    }
    gruzomarket.reference.grpc.GetProductCategoryIdsRequest other = (gruzomarket.reference.grpc.GetProductCategoryIdsRequest) obj;

    if (!getProductIdsList()
        .equals(other.getProductIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProductIdsCount() > 0) {
      hash = (37 * hash) + PRODUCT_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getProductIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gruzomarket.reference.grpc.GetProductCategoryIdsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reference.GetProductCategoryIdsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reference.GetProductCategoryIdsRequest)
      gruzomarket.reference.grpc.GetProductCategoryIdsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_GetProductCategoryIdsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_GetProductCategoryIdsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gruzomarket.reference.grpc.GetProductCategoryIdsRequest.class, gruzomarket.reference.grpc.GetProductCategoryIdsRequest.Builder.class);
    }

    // Construct using gruzomarket.reference.grpc.GetProductCategoryIdsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      productIds_ = emptyLongList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_GetProductCategoryIdsRequest_descriptor;
    }

    @java.lang.Override
    public gruzomarket.reference.grpc.GetProductCategoryIdsRequest getDefaultInstanceForType() {
      return gruzomarket.reference.grpc.GetProductCategoryIdsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public gruzomarket.reference.grpc.GetProductCategoryIdsRequest build() {
      gruzomarket.reference.grpc.GetProductCategoryIdsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gruzomarket.reference.grpc.GetProductCategoryIdsRequest buildPartial() {
      gruzomarket.reference.grpc.GetProductCategoryIdsRequest result = new gruzomarket.reference.grpc.GetProductCategoryIdsRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(gruzomarket.reference.grpc.GetProductCategoryIdsRequest result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        productIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.productIds_ = productIds_;
    }

    private void buildPartial0(gruzomarket.reference.grpc.GetProductCategoryIdsRequest result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gruzomarket.reference.grpc.GetProductCategoryIdsRequest) {
        return mergeFrom((gruzomarket.reference.grpc.GetProductCategoryIdsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gruzomarket.reference.grpc.GetProductCategoryIdsRequest other) {
      if (other == gruzomarket.reference.grpc.GetProductCategoryIdsRequest.getDefaultInstance()) return this;
      if (!other.productIds_.isEmpty()) {
        if (productIds_.isEmpty()) {
          productIds_ = other.productIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureProductIdsIsMutable();
          productIds_.addAll(other.productIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              long v = input.readInt64();
              ensureProductIdsIsMutable();
              productIds_.addLong(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureProductIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                productIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList productIds_ = emptyLongList();
    private void ensureProductIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        productIds_ = mutableCopy(productIds_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated int64 product_ids = 1;</code>
     * @return A list containing the productIds.
     */
    public java.util.List<java.lang.Long>
        getProductIdsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(productIds_) : productIds_;
    }
    /**
     * <code>repeated int64 product_ids = 1;</code>
     * @return The count of productIds.
     */
    public int getProductIdsCount() {
      return productIds_.size();
    }
    /**
     * <code>repeated int64 product_ids = 1;</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    public long getProductIds(int index) {
      return productIds_.getLong(index);
    }
    /**
     * <code>repeated int64 product_ids = 1;</code>
     * @param index The index to set the value at.
     * @param value The productIds to set.
     * @return This builder for chaining.
     */
    public Builder setProductIds(
        int index, long value) {
      
      ensureProductIdsIsMutable();
      productIds_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 product_ids = 1;</code>
     * @param value The productIds to add.
     * @return This builder for chaining.
     */
    public Builder addProductIds(long value) {
      
      ensureProductIdsIsMutable();
      productIds_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 product_ids = 1;</code>
     * @param values The productIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllProductIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureProductIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, productIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 product_ids = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductIds() {
      productIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:reference.GetProductCategoryIdsRequest)
  }

  // @@protoc_insertion_point(class_scope:reference.GetProductCategoryIdsRequest)
  private static final gruzomarket.reference.grpc.GetProductCategoryIdsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gruzomarket.reference.grpc.GetProductCategoryIdsRequest();
  }

  public static gruzomarket.reference.grpc.GetProductCategoryIdsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetProductCategoryIdsRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetProductCategoryIdsRequest>() {
    @java.lang.Override
    public GetProductCategoryIdsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetProductCategoryIdsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetProductCategoryIdsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gruzomarket.reference.grpc.GetProductCategoryIdsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

