// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface ListBrandsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.ListBrandsRequest)
    com.google.protobuf.MessageOrBuilder {
}
