// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

/**
 * Protobuf type {@code reference.ProductResponse}
 */
public final class ProductResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:reference.ProductResponse)
    ProductResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductResponse.newBuilder() to construct.
  private ProductResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductResponse() {
    name_ = "";
    article_ = "";
    description_ = "";
    categoryName_ = "";
    originalAuto_ = "";
    imageUrl_ = "";
    additionalImageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_ProductResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_ProductResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gruzomarket.reference.grpc.ProductResponse.class, gruzomarket.reference.grpc.ProductResponse.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARTICLE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object article_ = "";
  /**
   * <code>string article = 3;</code>
   * @return The article.
   */
  @java.lang.Override
  public java.lang.String getArticle() {
    java.lang.Object ref = article_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      article_ = s;
      return s;
    }
  }
  /**
   * <code>string article = 3;</code>
   * @return The bytes for article.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArticleBytes() {
    java.lang.Object ref = article_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      article_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 5;
  private double price_ = 0D;
  /**
   * <code>double price = 5;</code>
   * @return The price.
   */
  @java.lang.Override
  public double getPrice() {
    return price_;
  }

  public static final int QUANTITY_FIELD_NUMBER = 6;
  private int quantity_ = 0;
  /**
   * <code>int32 quantity = 6;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  public static final int CATEGORY_ID_FIELD_NUMBER = 7;
  private long categoryId_ = 0L;
  /**
   * <code>int64 category_id = 7;</code>
   * @return The categoryId.
   */
  @java.lang.Override
  public long getCategoryId() {
    return categoryId_;
  }

  public static final int CATEGORY_NAME_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object categoryName_ = "";
  /**
   * <code>string category_name = 8;</code>
   * @return The categoryName.
   */
  @java.lang.Override
  public java.lang.String getCategoryName() {
    java.lang.Object ref = categoryName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      categoryName_ = s;
      return s;
    }
  }
  /**
   * <code>string category_name = 8;</code>
   * @return The bytes for categoryName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCategoryNameBytes() {
    java.lang.Object ref = categoryName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      categoryName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGINAL_AUTO_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object originalAuto_ = "";
  /**
   * <code>string original_auto = 9;</code>
   * @return The originalAuto.
   */
  @java.lang.Override
  public java.lang.String getOriginalAuto() {
    java.lang.Object ref = originalAuto_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      originalAuto_ = s;
      return s;
    }
  }
  /**
   * <code>string original_auto = 9;</code>
   * @return The bytes for originalAuto.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginalAutoBytes() {
    java.lang.Object ref = originalAuto_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      originalAuto_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_VISIBLE_FIELD_NUMBER = 10;
  private boolean isVisible_ = false;
  /**
   * <code>bool is_visible = 10;</code>
   * @return The isVisible.
   */
  @java.lang.Override
  public boolean getIsVisible() {
    return isVisible_;
  }

  public static final int IMAGE_URL_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object imageUrl_ = "";
  /**
   * <code>string image_url = 11;</code>
   * @return The imageUrl.
   */
  @java.lang.Override
  public java.lang.String getImageUrl() {
    java.lang.Object ref = imageUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imageUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string image_url = 11;</code>
   * @return The bytes for imageUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageUrlBytes() {
    java.lang.Object ref = imageUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imageUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDITIONAL_IMAGE_URLS_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList additionalImageUrls_;
  /**
   * <code>repeated string additional_image_urls = 12;</code>
   * @return A list containing the additionalImageUrls.
   */
  public com.google.protobuf.ProtocolStringList
      getAdditionalImageUrlsList() {
    return additionalImageUrls_;
  }
  /**
   * <code>repeated string additional_image_urls = 12;</code>
   * @return The count of additionalImageUrls.
   */
  public int getAdditionalImageUrlsCount() {
    return additionalImageUrls_.size();
  }
  /**
   * <code>repeated string additional_image_urls = 12;</code>
   * @param index The index of the element to return.
   * @return The additionalImageUrls at the given index.
   */
  public java.lang.String getAdditionalImageUrls(int index) {
    return additionalImageUrls_.get(index);
  }
  /**
   * <code>repeated string additional_image_urls = 12;</code>
   * @param index The index of the value to return.
   * @return The bytes of the additionalImageUrls at the given index.
   */
  public com.google.protobuf.ByteString
      getAdditionalImageUrlsBytes(int index) {
    return additionalImageUrls_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(article_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, article_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      output.writeDouble(5, price_);
    }
    if (quantity_ != 0) {
      output.writeInt32(6, quantity_);
    }
    if (categoryId_ != 0L) {
      output.writeInt64(7, categoryId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(categoryName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, categoryName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalAuto_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, originalAuto_);
    }
    if (isVisible_ != false) {
      output.writeBool(10, isVisible_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, imageUrl_);
    }
    for (int i = 0; i < additionalImageUrls_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, additionalImageUrls_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(article_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, article_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, price_);
    }
    if (quantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, quantity_);
    }
    if (categoryId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, categoryId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(categoryName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, categoryName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalAuto_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, originalAuto_);
    }
    if (isVisible_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isVisible_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, imageUrl_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < additionalImageUrls_.size(); i++) {
        dataSize += computeStringSizeNoTag(additionalImageUrls_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAdditionalImageUrlsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gruzomarket.reference.grpc.ProductResponse)) {
      return super.equals(obj);
    }
    gruzomarket.reference.grpc.ProductResponse other = (gruzomarket.reference.grpc.ProductResponse) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getArticle()
        .equals(other.getArticle())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (getQuantity()
        != other.getQuantity()) return false;
    if (getCategoryId()
        != other.getCategoryId()) return false;
    if (!getCategoryName()
        .equals(other.getCategoryName())) return false;
    if (!getOriginalAuto()
        .equals(other.getOriginalAuto())) return false;
    if (getIsVisible()
        != other.getIsVisible()) return false;
    if (!getImageUrl()
        .equals(other.getImageUrl())) return false;
    if (!getAdditionalImageUrlsList()
        .equals(other.getAdditionalImageUrlsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + ARTICLE_FIELD_NUMBER;
    hash = (53 * hash) + getArticle().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity();
    hash = (37 * hash) + CATEGORY_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCategoryId());
    hash = (37 * hash) + CATEGORY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCategoryName().hashCode();
    hash = (37 * hash) + ORIGINAL_AUTO_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalAuto().hashCode();
    hash = (37 * hash) + IS_VISIBLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsVisible());
    hash = (37 * hash) + IMAGE_URL_FIELD_NUMBER;
    hash = (53 * hash) + getImageUrl().hashCode();
    if (getAdditionalImageUrlsCount() > 0) {
      hash = (37 * hash) + ADDITIONAL_IMAGE_URLS_FIELD_NUMBER;
      hash = (53 * hash) + getAdditionalImageUrlsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gruzomarket.reference.grpc.ProductResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gruzomarket.reference.grpc.ProductResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.ProductResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gruzomarket.reference.grpc.ProductResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.ProductResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gruzomarket.reference.grpc.ProductResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.ProductResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gruzomarket.reference.grpc.ProductResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.ProductResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gruzomarket.reference.grpc.ProductResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.ProductResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gruzomarket.reference.grpc.ProductResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gruzomarket.reference.grpc.ProductResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reference.ProductResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reference.ProductResponse)
      gruzomarket.reference.grpc.ProductResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_ProductResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_ProductResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gruzomarket.reference.grpc.ProductResponse.class, gruzomarket.reference.grpc.ProductResponse.Builder.class);
    }

    // Construct using gruzomarket.reference.grpc.ProductResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      name_ = "";
      article_ = "";
      description_ = "";
      price_ = 0D;
      quantity_ = 0;
      categoryId_ = 0L;
      categoryName_ = "";
      originalAuto_ = "";
      isVisible_ = false;
      imageUrl_ = "";
      additionalImageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000800);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_ProductResponse_descriptor;
    }

    @java.lang.Override
    public gruzomarket.reference.grpc.ProductResponse getDefaultInstanceForType() {
      return gruzomarket.reference.grpc.ProductResponse.getDefaultInstance();
    }

    @java.lang.Override
    public gruzomarket.reference.grpc.ProductResponse build() {
      gruzomarket.reference.grpc.ProductResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gruzomarket.reference.grpc.ProductResponse buildPartial() {
      gruzomarket.reference.grpc.ProductResponse result = new gruzomarket.reference.grpc.ProductResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(gruzomarket.reference.grpc.ProductResponse result) {
      if (((bitField0_ & 0x00000800) != 0)) {
        additionalImageUrls_ = additionalImageUrls_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000800);
      }
      result.additionalImageUrls_ = additionalImageUrls_;
    }

    private void buildPartial0(gruzomarket.reference.grpc.ProductResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.article_ = article_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.price_ = price_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.quantity_ = quantity_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.categoryId_ = categoryId_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.categoryName_ = categoryName_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.originalAuto_ = originalAuto_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.isVisible_ = isVisible_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.imageUrl_ = imageUrl_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gruzomarket.reference.grpc.ProductResponse) {
        return mergeFrom((gruzomarket.reference.grpc.ProductResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gruzomarket.reference.grpc.ProductResponse other) {
      if (other == gruzomarket.reference.grpc.ProductResponse.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getArticle().isEmpty()) {
        article_ = other.article_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (other.getQuantity() != 0) {
        setQuantity(other.getQuantity());
      }
      if (other.getCategoryId() != 0L) {
        setCategoryId(other.getCategoryId());
      }
      if (!other.getCategoryName().isEmpty()) {
        categoryName_ = other.categoryName_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getOriginalAuto().isEmpty()) {
        originalAuto_ = other.originalAuto_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.getIsVisible() != false) {
        setIsVisible(other.getIsVisible());
      }
      if (!other.getImageUrl().isEmpty()) {
        imageUrl_ = other.imageUrl_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.additionalImageUrls_.isEmpty()) {
        if (additionalImageUrls_.isEmpty()) {
          additionalImageUrls_ = other.additionalImageUrls_;
          bitField0_ = (bitField0_ & ~0x00000800);
        } else {
          ensureAdditionalImageUrlsIsMutable();
          additionalImageUrls_.addAll(other.additionalImageUrls_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              article_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 41: {
              price_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 48: {
              quantity_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              categoryId_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              categoryName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              originalAuto_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              isVisible_ = input.readBool();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              imageUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAdditionalImageUrlsIsMutable();
              additionalImageUrls_.add(s);
              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object article_ = "";
    /**
     * <code>string article = 3;</code>
     * @return The article.
     */
    public java.lang.String getArticle() {
      java.lang.Object ref = article_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        article_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string article = 3;</code>
     * @return The bytes for article.
     */
    public com.google.protobuf.ByteString
        getArticleBytes() {
      java.lang.Object ref = article_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        article_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string article = 3;</code>
     * @param value The article to set.
     * @return This builder for chaining.
     */
    public Builder setArticle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      article_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string article = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearArticle() {
      article_ = getDefaultInstance().getArticle();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string article = 3;</code>
     * @param value The bytes for article to set.
     * @return This builder for chaining.
     */
    public Builder setArticleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      article_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <code>double price = 5;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 5;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      bitField0_ = (bitField0_ & ~0x00000010);
      price_ = 0D;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <code>int32 quantity = 6;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>int32 quantity = 6;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      
      quantity_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 quantity = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000020);
      quantity_ = 0;
      onChanged();
      return this;
    }

    private long categoryId_ ;
    /**
     * <code>int64 category_id = 7;</code>
     * @return The categoryId.
     */
    @java.lang.Override
    public long getCategoryId() {
      return categoryId_;
    }
    /**
     * <code>int64 category_id = 7;</code>
     * @param value The categoryId to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryId(long value) {
      
      categoryId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 category_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategoryId() {
      bitField0_ = (bitField0_ & ~0x00000040);
      categoryId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object categoryName_ = "";
    /**
     * <code>string category_name = 8;</code>
     * @return The categoryName.
     */
    public java.lang.String getCategoryName() {
      java.lang.Object ref = categoryName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        categoryName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string category_name = 8;</code>
     * @return The bytes for categoryName.
     */
    public com.google.protobuf.ByteString
        getCategoryNameBytes() {
      java.lang.Object ref = categoryName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        categoryName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string category_name = 8;</code>
     * @param value The categoryName to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      categoryName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string category_name = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategoryName() {
      categoryName_ = getDefaultInstance().getCategoryName();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string category_name = 8;</code>
     * @param value The bytes for categoryName to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      categoryName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object originalAuto_ = "";
    /**
     * <code>string original_auto = 9;</code>
     * @return The originalAuto.
     */
    public java.lang.String getOriginalAuto() {
      java.lang.Object ref = originalAuto_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originalAuto_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string original_auto = 9;</code>
     * @return The bytes for originalAuto.
     */
    public com.google.protobuf.ByteString
        getOriginalAutoBytes() {
      java.lang.Object ref = originalAuto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originalAuto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string original_auto = 9;</code>
     * @param value The originalAuto to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalAuto(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      originalAuto_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string original_auto = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalAuto() {
      originalAuto_ = getDefaultInstance().getOriginalAuto();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string original_auto = 9;</code>
     * @param value The bytes for originalAuto to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalAutoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      originalAuto_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private boolean isVisible_ ;
    /**
     * <code>bool is_visible = 10;</code>
     * @return The isVisible.
     */
    @java.lang.Override
    public boolean getIsVisible() {
      return isVisible_;
    }
    /**
     * <code>bool is_visible = 10;</code>
     * @param value The isVisible to set.
     * @return This builder for chaining.
     */
    public Builder setIsVisible(boolean value) {
      
      isVisible_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_visible = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsVisible() {
      bitField0_ = (bitField0_ & ~0x00000200);
      isVisible_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object imageUrl_ = "";
    /**
     * <code>string image_url = 11;</code>
     * @return The imageUrl.
     */
    public java.lang.String getImageUrl() {
      java.lang.Object ref = imageUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string image_url = 11;</code>
     * @return The bytes for imageUrl.
     */
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string image_url = 11;</code>
     * @param value The imageUrl to set.
     * @return This builder for chaining.
     */
    public Builder setImageUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      imageUrl_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string image_url = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageUrl() {
      imageUrl_ = getDefaultInstance().getImageUrl();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string image_url = 11;</code>
     * @param value The bytes for imageUrl to set.
     * @return This builder for chaining.
     */
    public Builder setImageUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      imageUrl_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList additionalImageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAdditionalImageUrlsIsMutable() {
      if (!((bitField0_ & 0x00000800) != 0)) {
        additionalImageUrls_ = new com.google.protobuf.LazyStringArrayList(additionalImageUrls_);
        bitField0_ |= 0x00000800;
       }
    }
    /**
     * <code>repeated string additional_image_urls = 12;</code>
     * @return A list containing the additionalImageUrls.
     */
    public com.google.protobuf.ProtocolStringList
        getAdditionalImageUrlsList() {
      return additionalImageUrls_.getUnmodifiableView();
    }
    /**
     * <code>repeated string additional_image_urls = 12;</code>
     * @return The count of additionalImageUrls.
     */
    public int getAdditionalImageUrlsCount() {
      return additionalImageUrls_.size();
    }
    /**
     * <code>repeated string additional_image_urls = 12;</code>
     * @param index The index of the element to return.
     * @return The additionalImageUrls at the given index.
     */
    public java.lang.String getAdditionalImageUrls(int index) {
      return additionalImageUrls_.get(index);
    }
    /**
     * <code>repeated string additional_image_urls = 12;</code>
     * @param index The index of the value to return.
     * @return The bytes of the additionalImageUrls at the given index.
     */
    public com.google.protobuf.ByteString
        getAdditionalImageUrlsBytes(int index) {
      return additionalImageUrls_.getByteString(index);
    }
    /**
     * <code>repeated string additional_image_urls = 12;</code>
     * @param index The index to set the value at.
     * @param value The additionalImageUrls to set.
     * @return This builder for chaining.
     */
    public Builder setAdditionalImageUrls(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAdditionalImageUrlsIsMutable();
      additionalImageUrls_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string additional_image_urls = 12;</code>
     * @param value The additionalImageUrls to add.
     * @return This builder for chaining.
     */
    public Builder addAdditionalImageUrls(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAdditionalImageUrlsIsMutable();
      additionalImageUrls_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string additional_image_urls = 12;</code>
     * @param values The additionalImageUrls to add.
     * @return This builder for chaining.
     */
    public Builder addAllAdditionalImageUrls(
        java.lang.Iterable<java.lang.String> values) {
      ensureAdditionalImageUrlsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, additionalImageUrls_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string additional_image_urls = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdditionalImageUrls() {
      additionalImageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string additional_image_urls = 12;</code>
     * @param value The bytes of the additionalImageUrls to add.
     * @return This builder for chaining.
     */
    public Builder addAdditionalImageUrlsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureAdditionalImageUrlsIsMutable();
      additionalImageUrls_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:reference.ProductResponse)
  }

  // @@protoc_insertion_point(class_scope:reference.ProductResponse)
  private static final gruzomarket.reference.grpc.ProductResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gruzomarket.reference.grpc.ProductResponse();
  }

  public static gruzomarket.reference.grpc.ProductResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductResponse>
      PARSER = new com.google.protobuf.AbstractParser<ProductResponse>() {
    @java.lang.Override
    public ProductResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProductResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gruzomarket.reference.grpc.ProductResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

