// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface ProductListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.ProductListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .reference.ProductResponse products = 1;</code>
   */
  java.util.List<gruzomarket.reference.grpc.ProductResponse> 
      getProductsList();
  /**
   * <code>repeated .reference.ProductResponse products = 1;</code>
   */
  gruzomarket.reference.grpc.ProductResponse getProducts(int index);
  /**
   * <code>repeated .reference.ProductResponse products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .reference.ProductResponse products = 1;</code>
   */
  java.util.List<? extends gruzomarket.reference.grpc.ProductResponseOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .reference.ProductResponse products = 1;</code>
   */
  gruzomarket.reference.grpc.ProductResponseOrBuilder getProductsOrBuilder(
      int index);
}
