// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

/**
 * Protobuf type {@code reference.ProductCategoryIdsResponse}
 */
public final class ProductCategoryIdsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:reference.ProductCategoryIdsResponse)
    ProductCategoryIdsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductCategoryIdsResponse.newBuilder() to construct.
  private ProductCategoryIdsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductCategoryIdsResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductCategoryIdsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_ProductCategoryIdsResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetProductCategoryMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_ProductCategoryIdsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gruzomarket.reference.grpc.ProductCategoryIdsResponse.class, gruzomarket.reference.grpc.ProductCategoryIdsResponse.Builder.class);
  }

  public static final int PRODUCT_CATEGORY_MAP_FIELD_NUMBER = 1;
  private static final class ProductCategoryMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Long, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Long, java.lang.Long>newDefaultInstance(
                gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_ProductCategoryIdsResponse_ProductCategoryMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L,
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.Long, java.lang.Long> productCategoryMap_;
  private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
  internalGetProductCategoryMap() {
    if (productCategoryMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ProductCategoryMapDefaultEntryHolder.defaultEntry);
    }
    return productCategoryMap_;
  }
  public int getProductCategoryMapCount() {
    return internalGetProductCategoryMap().getMap().size();
  }
  /**
   * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
   */
  @java.lang.Override
  public boolean containsProductCategoryMap(
      long key) {
    
    return internalGetProductCategoryMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getProductCategoryMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Long, java.lang.Long> getProductCategoryMap() {
    return getProductCategoryMapMap();
  }
  /**
   * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.Long, java.lang.Long> getProductCategoryMapMap() {
    return internalGetProductCategoryMap().getMap();
  }
  /**
   * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
   */
  @java.lang.Override
  public long getProductCategoryMapOrDefault(
      long key,
      long defaultValue) {
    
    java.util.Map<java.lang.Long, java.lang.Long> map =
        internalGetProductCategoryMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
   */
  @java.lang.Override
  public long getProductCategoryMapOrThrow(
      long key) {
    
    java.util.Map<java.lang.Long, java.lang.Long> map =
        internalGetProductCategoryMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeLongMapTo(
        output,
        internalGetProductCategoryMap(),
        ProductCategoryMapDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Long, java.lang.Long> entry
         : internalGetProductCategoryMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Long, java.lang.Long>
      productCategoryMap__ = ProductCategoryMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, productCategoryMap__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gruzomarket.reference.grpc.ProductCategoryIdsResponse)) {
      return super.equals(obj);
    }
    gruzomarket.reference.grpc.ProductCategoryIdsResponse other = (gruzomarket.reference.grpc.ProductCategoryIdsResponse) obj;

    if (!internalGetProductCategoryMap().equals(
        other.internalGetProductCategoryMap())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetProductCategoryMap().getMap().isEmpty()) {
      hash = (37 * hash) + PRODUCT_CATEGORY_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetProductCategoryMap().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gruzomarket.reference.grpc.ProductCategoryIdsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reference.ProductCategoryIdsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reference.ProductCategoryIdsResponse)
      gruzomarket.reference.grpc.ProductCategoryIdsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_ProductCategoryIdsResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetProductCategoryMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableProductCategoryMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_ProductCategoryIdsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gruzomarket.reference.grpc.ProductCategoryIdsResponse.class, gruzomarket.reference.grpc.ProductCategoryIdsResponse.Builder.class);
    }

    // Construct using gruzomarket.reference.grpc.ProductCategoryIdsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableProductCategoryMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gruzomarket.reference.grpc.ReferenceServiceOuterClass.internal_static_reference_ProductCategoryIdsResponse_descriptor;
    }

    @java.lang.Override
    public gruzomarket.reference.grpc.ProductCategoryIdsResponse getDefaultInstanceForType() {
      return gruzomarket.reference.grpc.ProductCategoryIdsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public gruzomarket.reference.grpc.ProductCategoryIdsResponse build() {
      gruzomarket.reference.grpc.ProductCategoryIdsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gruzomarket.reference.grpc.ProductCategoryIdsResponse buildPartial() {
      gruzomarket.reference.grpc.ProductCategoryIdsResponse result = new gruzomarket.reference.grpc.ProductCategoryIdsResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(gruzomarket.reference.grpc.ProductCategoryIdsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.productCategoryMap_ = internalGetProductCategoryMap();
        result.productCategoryMap_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gruzomarket.reference.grpc.ProductCategoryIdsResponse) {
        return mergeFrom((gruzomarket.reference.grpc.ProductCategoryIdsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gruzomarket.reference.grpc.ProductCategoryIdsResponse other) {
      if (other == gruzomarket.reference.grpc.ProductCategoryIdsResponse.getDefaultInstance()) return this;
      internalGetMutableProductCategoryMap().mergeFrom(
          other.internalGetProductCategoryMap());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.Long, java.lang.Long>
              productCategoryMap__ = input.readMessage(
                  ProductCategoryMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableProductCategoryMap().getMutableMap().put(
                  productCategoryMap__.getKey(), productCategoryMap__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.Long, java.lang.Long> productCategoryMap_;
    private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
        internalGetProductCategoryMap() {
      if (productCategoryMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ProductCategoryMapDefaultEntryHolder.defaultEntry);
      }
      return productCategoryMap_;
    }
    private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
        internalGetMutableProductCategoryMap() {
      if (productCategoryMap_ == null) {
        productCategoryMap_ = com.google.protobuf.MapField.newMapField(
            ProductCategoryMapDefaultEntryHolder.defaultEntry);
      }
      if (!productCategoryMap_.isMutable()) {
        productCategoryMap_ = productCategoryMap_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return productCategoryMap_;
    }
    public int getProductCategoryMapCount() {
      return internalGetProductCategoryMap().getMap().size();
    }
    /**
     * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
     */
    @java.lang.Override
    public boolean containsProductCategoryMap(
        long key) {
      
      return internalGetProductCategoryMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getProductCategoryMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Long> getProductCategoryMap() {
      return getProductCategoryMapMap();
    }
    /**
     * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Long, java.lang.Long> getProductCategoryMapMap() {
      return internalGetProductCategoryMap().getMap();
    }
    /**
     * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
     */
    @java.lang.Override
    public long getProductCategoryMapOrDefault(
        long key,
        long defaultValue) {
      
      java.util.Map<java.lang.Long, java.lang.Long> map =
          internalGetProductCategoryMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
     */
    @java.lang.Override
    public long getProductCategoryMapOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, java.lang.Long> map =
          internalGetProductCategoryMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearProductCategoryMap() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableProductCategoryMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
     */
    public Builder removeProductCategoryMap(
        long key) {
      
      internalGetMutableProductCategoryMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Long>
        getMutableProductCategoryMap() {
      bitField0_ |= 0x00000001;
      return internalGetMutableProductCategoryMap().getMutableMap();
    }
    /**
     * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
     */
    public Builder putProductCategoryMap(
        long key,
        long value) {
      
      
      internalGetMutableProductCategoryMap().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
     */
    public Builder putAllProductCategoryMap(
        java.util.Map<java.lang.Long, java.lang.Long> values) {
      internalGetMutableProductCategoryMap().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:reference.ProductCategoryIdsResponse)
  }

  // @@protoc_insertion_point(class_scope:reference.ProductCategoryIdsResponse)
  private static final gruzomarket.reference.grpc.ProductCategoryIdsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gruzomarket.reference.grpc.ProductCategoryIdsResponse();
  }

  public static gruzomarket.reference.grpc.ProductCategoryIdsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductCategoryIdsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ProductCategoryIdsResponse>() {
    @java.lang.Override
    public ProductCategoryIdsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProductCategoryIdsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductCategoryIdsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gruzomarket.reference.grpc.ProductCategoryIdsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

