// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface ProductCategoryIdsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.ProductCategoryIdsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
   */
  int getProductCategoryMapCount();
  /**
   * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
   */
  boolean containsProductCategoryMap(
      long key);
  /**
   * Use {@link #getProductCategoryMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, java.lang.Long>
  getProductCategoryMap();
  /**
   * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
   */
  java.util.Map<java.lang.Long, java.lang.Long>
  getProductCategoryMapMap();
  /**
   * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
   */
  long getProductCategoryMapOrDefault(
      long key,
      long defaultValue);
  /**
   * <code>map&lt;int64, int64&gt; product_category_map = 1;</code>
   */
  long getProductCategoryMapOrThrow(
      long key);
}
