// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reference.ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string article = 3;</code>
   * @return The article.
   */
  java.lang.String getArticle();
  /**
   * <code>string article = 3;</code>
   * @return The bytes for article.
   */
  com.google.protobuf.ByteString
      getArticleBytes();

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>double price = 5;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>int32 quantity = 6;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>int64 category_id = 7;</code>
   * @return The categoryId.
   */
  long getCategoryId();

  /**
   * <code>string category_name = 8;</code>
   * @return The categoryName.
   */
  java.lang.String getCategoryName();
  /**
   * <code>string category_name = 8;</code>
   * @return The bytes for categoryName.
   */
  com.google.protobuf.ByteString
      getCategoryNameBytes();

  /**
   * <code>string original_auto = 9;</code>
   * @return The originalAuto.
   */
  java.lang.String getOriginalAuto();
  /**
   * <code>string original_auto = 9;</code>
   * @return The bytes for originalAuto.
   */
  com.google.protobuf.ByteString
      getOriginalAutoBytes();

  /**
   * <code>bool is_visible = 10;</code>
   * @return The isVisible.
   */
  boolean getIsVisible();

  /**
   * <code>string image_url = 11;</code>
   * @return The imageUrl.
   */
  java.lang.String getImageUrl();
  /**
   * <code>string image_url = 11;</code>
   * @return The bytes for imageUrl.
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();

  /**
   * <code>repeated string additional_image_urls = 12;</code>
   * @return A list containing the additionalImageUrls.
   */
  java.util.List<java.lang.String>
      getAdditionalImageUrlsList();
  /**
   * <code>repeated string additional_image_urls = 12;</code>
   * @return The count of additionalImageUrls.
   */
  int getAdditionalImageUrlsCount();
  /**
   * <code>repeated string additional_image_urls = 12;</code>
   * @param index The index of the element to return.
   * @return The additionalImageUrls at the given index.
   */
  java.lang.String getAdditionalImageUrls(int index);
  /**
   * <code>repeated string additional_image_urls = 12;</code>
   * @param index The index of the value to return.
   * @return The bytes of the additionalImageUrls at the given index.
   */
  com.google.protobuf.ByteString
      getAdditionalImageUrlsBytes(int index);
}
