// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_service.proto

package gruzomarket.reference.grpc;

public final class ReferenceServiceOuterClass {
  private ReferenceServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_ProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_CategoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_CategoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_BrandResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_BrandResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_CategoryGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_CategoryGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_GetProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_GetProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_GetProductsByIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_GetProductsByIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_SearchProductsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_SearchProductsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_DeductStockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_DeductStockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_DeductStockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_DeductStockResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_GetCategoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_GetCategoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_ListCategoriesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_ListCategoriesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_ListCategoryGroupsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_ListCategoryGroupsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_GetBrandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_GetBrandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_ListBrandsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_ListBrandsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_ExistsBrandByNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_ExistsBrandByNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_ExistsProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_ExistsProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_GetBrandsByProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_GetBrandsByProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_GetProductsByBrandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_GetProductsByBrandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_GetProductCategoryIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_GetProductCategoryIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_ProductCategoryIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_ProductCategoryIdsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_ProductCategoryIdsResponse_ProductCategoryMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_ProductCategoryIdsResponse_ProductCategoryMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_ExistsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_ExistsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_ProductListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_ProductListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_CategoryListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_CategoryListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_CategoryGroupListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_CategoryGroupListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_BrandListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_BrandListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reference_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reference_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027reference_service.proto\022\treference\"\373\001\n" +
      "\017ProductResponse\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001" +
      "(\t\022\017\n\007article\030\003 \001(\t\022\023\n\013description\030\004 \001(\t" +
      "\022\r\n\005price\030\005 \001(\001\022\020\n\010quantity\030\006 \001(\005\022\023\n\013cat" +
      "egory_id\030\007 \001(\003\022\025\n\rcategory_name\030\010 \001(\t\022\025\n" +
      "\roriginal_auto\030\t \001(\t\022\022\n\nis_visible\030\n \001(\010" +
      "\022\021\n\timage_url\030\013 \001(\t\022\035\n\025additional_image_" +
      "urls\030\014 \003(\t\"i\n\020CategoryResponse\022\n\n\002id\030\001 \001" +
      "(\003\022\014\n\004name\030\002 \001(\t\022\021\n\tparent_id\030\003 \001(\003\022\025\n\rp" +
      "roduct_count\030\004 \001(\005\022\021\n\timage_url\030\005 \001(\t\"@\n" +
      "\rBrandResponse\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t" +
      "\022\025\n\rproduct_count\030\003 \001(\005\"\\\n\025CategoryGroup" +
      "Response\022\022\n\ngroup_name\030\001 \001(\t\022/\n\ncategori" +
      "es\030\002 \003(\0132\033.reference.CategoryResponse\"\037\n" +
      "\021GetProductRequest\022\n\n\002id\030\001 \001(\003\"&\n\027GetPro" +
      "ductsByIdsRequest\022\013\n\003ids\030\001 \003(\003\"&\n\025Search" +
      "ProductsRequest\022\r\n\005query\030\001 \001(\t\":\n\022Deduct" +
      "StockRequest\022\022\n\nproduct_id\030\001 \001(\003\022\020\n\010quan" +
      "tity\030\002 \001(\005\"7\n\023DeductStockResponse\022\017\n\007suc" +
      "cess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\" \n\022GetCatego" +
      "ryRequest\022\n\n\002id\030\001 \001(\003\"\027\n\025ListCategoriesR" +
      "equest\"\033\n\031ListCategoryGroupsRequest\"\035\n\017G" +
      "etBrandRequest\022\n\n\002id\030\001 \001(\003\"\023\n\021ListBrands" +
      "Request\"(\n\030ExistsBrandByNameRequest\022\014\n\004n" +
      "ame\030\001 \001(\t\"\"\n\024ExistsProductRequest\022\n\n\002id\030" +
      "\001 \001(\003\"/\n\031GetBrandsByProductRequest\022\022\n\npr" +
      "oduct_id\030\001 \001(\003\"-\n\031GetProductsByBrandRequ" +
      "est\022\020\n\010brand_id\030\001 \001(\003\"3\n\034GetProductCateg" +
      "oryIdsRequest\022\023\n\013product_ids\030\001 \003(\003\"\264\001\n\032P" +
      "roductCategoryIdsResponse\022[\n\024product_cat" +
      "egory_map\030\001 \003(\0132=.reference.ProductCateg" +
      "oryIdsResponse.ProductCategoryMapEntry\0329" +
      "\n\027ProductCategoryMapEntry\022\013\n\003key\030\001 \001(\003\022\r" +
      "\n\005value\030\002 \001(\003:\0028\001\" \n\016ExistsResponse\022\016\n\006e" +
      "xists\030\001 \001(\010\"C\n\023ProductListResponse\022,\n\010pr" +
      "oducts\030\001 \003(\0132\032.reference.ProductResponse" +
      "\"G\n\024CategoryListResponse\022/\n\ncategories\030\001" +
      " \003(\0132\033.reference.CategoryResponse\"M\n\031Cat" +
      "egoryGroupListResponse\0220\n\006groups\030\001 \003(\0132 " +
      ".reference.CategoryGroupResponse\"=\n\021Bran" +
      "dListResponse\022(\n\006brands\030\001 \003(\0132\030.referenc" +
      "e.BrandResponse\"\024\n\022HealthCheckRequest\"%\n" +
      "\023HealthCheckResponse\022\016\n\006status\030\001 \001(\t2\361\t\n" +
      "\020ReferenceService\022F\n\nGetProduct\022\034.refere" +
      "nce.GetProductRequest\032\032.reference.Produc" +
      "tResponse\022V\n\020GetProductsByIds\022\".referenc" +
      "e.GetProductsByIdsRequest\032\036.reference.Pr" +
      "oductListResponse\022R\n\016SearchProducts\022 .re" +
      "ference.SearchProductsRequest\032\036.referenc" +
      "e.ProductListResponse\022L\n\013DeductStock\022\035.r" +
      "eference.DeductStockRequest\032\036.reference." +
      "DeductStockResponse\022I\n\013GetCategory\022\035.ref" +
      "erence.GetCategoryRequest\032\033.reference.Ca" +
      "tegoryResponse\022S\n\016ListCategories\022 .refer" +
      "ence.ListCategoriesRequest\032\037.reference.C" +
      "ategoryListResponse\022`\n\022ListCategoryGroup" +
      "s\022$.reference.ListCategoryGroupsRequest\032" +
      "$.reference.CategoryGroupListResponse\022@\n" +
      "\010GetBrand\022\032.reference.GetBrandRequest\032\030." +
      "reference.BrandResponse\022H\n\nListBrands\022\034." +
      "reference.ListBrandsRequest\032\034.reference." +
      "BrandListResponse\022S\n\021ExistsBrandByName\022#" +
      ".reference.ExistsBrandByNameRequest\032\031.re" +
      "ference.ExistsResponse\022X\n\022GetBrandsByPro" +
      "duct\022$.reference.GetBrandsByProductReque" +
      "st\032\034.reference.BrandListResponse\022Z\n\022GetP" +
      "roductsByBrand\022$.reference.GetProductsBy" +
      "BrandRequest\032\036.reference.ProductListResp" +
      "onse\022K\n\rExistsProduct\022\037.reference.Exists" +
      "ProductRequest\032\031.reference.ExistsRespons" +
      "e\022g\n\025GetProductCategoryIds\022\'.reference.G" +
      "etProductCategoryIdsRequest\032%.reference." +
      "ProductCategoryIdsResponse\022L\n\013HealthChec" +
      "k\022\035.reference.HealthCheckRequest\032\036.refer" +
      "ence.HealthCheckResponseB\036\n\032gruzomarket." +
      "reference.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_reference_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_reference_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_ProductResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Article", "Description", "Price", "Quantity", "CategoryId", "CategoryName", "OriginalAuto", "IsVisible", "ImageUrl", "AdditionalImageUrls", });
    internal_static_reference_CategoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_reference_CategoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_CategoryResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "ParentId", "ProductCount", "ImageUrl", });
    internal_static_reference_BrandResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_reference_BrandResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_BrandResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "ProductCount", });
    internal_static_reference_CategoryGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_reference_CategoryGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_CategoryGroupResponse_descriptor,
        new java.lang.String[] { "GroupName", "Categories", });
    internal_static_reference_GetProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_reference_GetProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_GetProductRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_reference_GetProductsByIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_reference_GetProductsByIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_GetProductsByIdsRequest_descriptor,
        new java.lang.String[] { "Ids", });
    internal_static_reference_SearchProductsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_reference_SearchProductsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_SearchProductsRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_reference_DeductStockRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_reference_DeductStockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_DeductStockRequest_descriptor,
        new java.lang.String[] { "ProductId", "Quantity", });
    internal_static_reference_DeductStockResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_reference_DeductStockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_DeductStockResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_reference_GetCategoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_reference_GetCategoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_GetCategoryRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_reference_ListCategoriesRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_reference_ListCategoriesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_ListCategoriesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_reference_ListCategoryGroupsRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_reference_ListCategoryGroupsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_ListCategoryGroupsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_reference_GetBrandRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_reference_GetBrandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_GetBrandRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_reference_ListBrandsRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_reference_ListBrandsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_ListBrandsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_reference_ExistsBrandByNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_reference_ExistsBrandByNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_ExistsBrandByNameRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_reference_ExistsProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_reference_ExistsProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_ExistsProductRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_reference_GetBrandsByProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_reference_GetBrandsByProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_GetBrandsByProductRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_reference_GetProductsByBrandRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_reference_GetProductsByBrandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_GetProductsByBrandRequest_descriptor,
        new java.lang.String[] { "BrandId", });
    internal_static_reference_GetProductCategoryIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_reference_GetProductCategoryIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_GetProductCategoryIdsRequest_descriptor,
        new java.lang.String[] { "ProductIds", });
    internal_static_reference_ProductCategoryIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_reference_ProductCategoryIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_ProductCategoryIdsResponse_descriptor,
        new java.lang.String[] { "ProductCategoryMap", });
    internal_static_reference_ProductCategoryIdsResponse_ProductCategoryMapEntry_descriptor =
      internal_static_reference_ProductCategoryIdsResponse_descriptor.getNestedTypes().get(0);
    internal_static_reference_ProductCategoryIdsResponse_ProductCategoryMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_ProductCategoryIdsResponse_ProductCategoryMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_reference_ExistsResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_reference_ExistsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_ExistsResponse_descriptor,
        new java.lang.String[] { "Exists", });
    internal_static_reference_ProductListResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_reference_ProductListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_ProductListResponse_descriptor,
        new java.lang.String[] { "Products", });
    internal_static_reference_CategoryListResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_reference_CategoryListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_CategoryListResponse_descriptor,
        new java.lang.String[] { "Categories", });
    internal_static_reference_CategoryGroupListResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_reference_CategoryGroupListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_CategoryGroupListResponse_descriptor,
        new java.lang.String[] { "Groups", });
    internal_static_reference_BrandListResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_reference_BrandListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_BrandListResponse_descriptor,
        new java.lang.String[] { "Brands", });
    internal_static_reference_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_reference_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_HealthCheckRequest_descriptor,
        new java.lang.String[] { });
    internal_static_reference_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_reference_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reference_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
