# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: menu_reference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'menu_reference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14menu_reference.proto\x12\rmenureference\"\x07\n\x05\x45mpty\"%\n\x15\x43reateCategoryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"+\n\x0f\x43\x61tegoryMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"J\n\x11\x43reateItemRequest\x12\x13\n\x0b\x63\x61tegory_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nprice_text\x18\x03 \x01(\t\"Z\n\x0bItemMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61tegory_id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x1c\n\x14price_decimal_string\x18\x04 \x01(\t\"!\n\x0eGetItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\"(\n\x0cMenuCategory\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"W\n\x08MenuItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61tegory_id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x1c\n\x14price_decimal_string\x18\x04 \x01(\t\"g\n\x0cMenuSnapshot\x12/\n\ncategories\x18\x01 \x03(\x0b\x32\x1b.menureference.MenuCategory\x12&\n\x05items\x18\x02 \x03(\x0b\x32\x17.menureference.MenuItem2\xb8\x02\n\rMenuReference\x12V\n\x0e\x43reateCategory\x12$.menureference.CreateCategoryRequest\x1a\x1e.menureference.CategoryMessage\x12J\n\nCreateItem\x12 .menureference.CreateItemRequest\x1a\x1a.menureference.ItemMessage\x12\x44\n\x07GetItem\x12\x1d.menureference.GetItemRequest\x1a\x1a.menureference.ItemMessage\x12=\n\x08ListMenu\x12\x14.menureference.Empty\x1a\x1b.menureference.MenuSnapshotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'menu_reference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=39
  _globals['_EMPTY']._serialized_end=46
  _globals['_CREATECATEGORYREQUEST']._serialized_start=48
  _globals['_CREATECATEGORYREQUEST']._serialized_end=85
  _globals['_CATEGORYMESSAGE']._serialized_start=87
  _globals['_CATEGORYMESSAGE']._serialized_end=130
  _globals['_CREATEITEMREQUEST']._serialized_start=132
  _globals['_CREATEITEMREQUEST']._serialized_end=206
  _globals['_ITEMMESSAGE']._serialized_start=208
  _globals['_ITEMMESSAGE']._serialized_end=298
  _globals['_GETITEMREQUEST']._serialized_start=300
  _globals['_GETITEMREQUEST']._serialized_end=333
  _globals['_MENUCATEGORY']._serialized_start=335
  _globals['_MENUCATEGORY']._serialized_end=375
  _globals['_MENUITEM']._serialized_start=377
  _globals['_MENUITEM']._serialized_end=464
  _globals['_MENUSNAPSHOT']._serialized_start=466
  _globals['_MENUSNAPSHOT']._serialized_end=569
  _globals['_MENUREFERENCE']._serialized_start=572
  _globals['_MENUREFERENCE']._serialized_end=884
# @@protoc_insertion_point(module_scope)
