# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cafe_app.grpc_gen import menu_reference_pb2 as menu__reference__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in menu_reference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MenuReferenceStub(object):
    """Справочник меню (Сервис B) для ЛР4.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCategory = channel.unary_unary(
                '/menureference.MenuReference/CreateCategory',
                request_serializer=menu__reference__pb2.CreateCategoryRequest.SerializeToString,
                response_deserializer=menu__reference__pb2.CategoryMessage.FromString,
                _registered_method=True)
        self.CreateItem = channel.unary_unary(
                '/menureference.MenuReference/CreateItem',
                request_serializer=menu__reference__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=menu__reference__pb2.ItemMessage.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/menureference.MenuReference/GetItem',
                request_serializer=menu__reference__pb2.GetItemRequest.SerializeToString,
                response_deserializer=menu__reference__pb2.ItemMessage.FromString,
                _registered_method=True)
        self.ListMenu = channel.unary_unary(
                '/menureference.MenuReference/ListMenu',
                request_serializer=menu__reference__pb2.Empty.SerializeToString,
                response_deserializer=menu__reference__pb2.MenuSnapshot.FromString,
                _registered_method=True)


class MenuReferenceServicer(object):
    """Справочник меню (Сервис B) для ЛР4.

    """

    def CreateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMenu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MenuReferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCategory,
                    request_deserializer=menu__reference__pb2.CreateCategoryRequest.FromString,
                    response_serializer=menu__reference__pb2.CategoryMessage.SerializeToString,
            ),
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=menu__reference__pb2.CreateItemRequest.FromString,
                    response_serializer=menu__reference__pb2.ItemMessage.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=menu__reference__pb2.GetItemRequest.FromString,
                    response_serializer=menu__reference__pb2.ItemMessage.SerializeToString,
            ),
            'ListMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMenu,
                    request_deserializer=menu__reference__pb2.Empty.FromString,
                    response_serializer=menu__reference__pb2.MenuSnapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'menureference.MenuReference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('menureference.MenuReference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MenuReference(object):
    """Справочник меню (Сервис B) для ЛР4.

    """

    @staticmethod
    def CreateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/menureference.MenuReference/CreateCategory',
            menu__reference__pb2.CreateCategoryRequest.SerializeToString,
            menu__reference__pb2.CategoryMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/menureference.MenuReference/CreateItem',
            menu__reference__pb2.CreateItemRequest.SerializeToString,
            menu__reference__pb2.ItemMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/menureference.MenuReference/GetItem',
            menu__reference__pb2.GetItemRequest.SerializeToString,
            menu__reference__pb2.ItemMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/menureference.MenuReference/ListMenu',
            menu__reference__pb2.Empty.SerializeToString,
            menu__reference__pb2.MenuSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
